export const universes = [
  { tag: "music", souls: "27M souls" },
  { tag: "movies", souls: "20M souls" },
  { tag: "food", souls: "14M souls" },
  { tag: "gaming", souls: "12M souls" },
  { tag: "anime", souls: "9M souls" },
  { tag: "animals", souls: "6.5M souls" },
  { tag: "outdoors", souls: "6.2M souls" },
  { tag: "technology", souls: "6.2M souls" },
  { tag: "books", souls: "6M souls" },
  { tag: "art", souls: "5.9M souls" },
  { tag: "memes", souls: "5.6M souls" },
  { tag: "psychology", souls: "5.1M souls" },
  { tag: "history", souls: "4.3M souls" },
  { tag: "culture", souls: "4.2M souls" },
  { tag: "learning", souls: "4.2M souls" },
  { tag: "science", souls: "3.4M souls" },
  { tag: "videos", souls: "3.1M souls" },
  { tag: "languages", souls: "2.5M souls" },
  { tag: "philosophy", souls: "2.4M souls" },
  { tag: "sports", souls: "2.1M souls" },
  { tag: "relationshipadvice", souls: "1.4M souls" },
  { tag: "fitness", souls: "1.1M souls" },
  { tag: "fashion", souls: "755K souls" },
  { tag: "country", souls: "643K souls" },
  { tag: "television", souls: "569K souls" },
  { tag: "news", souls: "278K souls" },
  { tag: "sex", souls: "155K souls" },
  { tag: "health", souls: "32K souls" },
  { tag: "work", souls: "22K souls" },
  { tag: "finance", souls: "20K souls" },
  { tag: "shopping", souls: "11K souls" },
  { tag: "religion", souls: "8.8K souls" },
  { tag: "home", souls: "5.8K souls" },
  { tag: "personality", souls: "3.4K souls" },
];

export const sidebarLinks = [
  "Home",
  "Match",
  "Messages",
  "Profile",
  "Personality Database",
  "Personality Tests",
  "Resources",
];

export const questionOfTheDay = {
  id: "q-0",
  code: "8HSkjc",
  title:
    "What would you choose: a relationship full of adventures or a peaceful one?",
  date: "11/7/2025",
  likes: 595,
  comments: 4077,
};

export const posts = [
  {
    id: "p-1",
    author: "Phoebe",
    badge: "INFJ",
    astro: "Aquarius",
    stats: "2 1",
    content: "A healthy relationship requires both adventure and peace.",
    likes: 293,
    comments: 19,
    time: "1mo",
  },
  {
    id: "p-2",
    author: "Kostas",
    badge: "ENFP",
    astro: "Cancer",
    stats: "9 1",
    content: "Y'all getting dates and relationships?!",
    likes: 101,
    comments: 19,
    time: "1mo",
  },
  {
    id: "p-3",
    author: "Jill",
    badge: "INFP",
    astro: "Pisces",
    stats: "0 0",
    content: "\"Full of adventures\" whatever that means... I think.",
    likes: 66,
    comments: 4,
    time: "1mo",
  },
  {
    id: "p-4",
    author: "Koffy",
    badge: "ESFJ",
    astro: "Sagittarius",
    stats: "8 7",
    content:
      "Never like a boring relationship... So I would choose both adventure and peace.",
    likes: 39,
    comments: 7,
    time: "1mo",
  },
  {
    id: "p-5",
    author: "Mira",
    badge: "INTP",
    astro: "Gemini",
    stats: "4 2",
    content: "Peace sounds great, but I still want a few spontaneous trips.",
    likes: 88,
    comments: 12,
    time: "3w",
  },
  {
    id: "p-6",
    author: "Rafa",
    badge: "ISTJ",
    astro: "Virgo",
    stats: "6 3",
    content: "Adventure is fun, but stability is what keeps me grounded.",
    likes: 142,
    comments: 25,
    time: "2w",
  },
  {
    id: "p-7",
    author: "Nadia",
    badge: "ENFJ",
    astro: "Leo",
    stats: "7 4",
    content: "Why not both? Little adventures inside a peaceful routine.",
    likes: 219,
    comments: 31,
    time: "2w",
  },
  {
    id: "p-8",
    author: "Theo",
    badge: "ISFP",
    astro: "Scorpio",
    stats: "1 0",
    content: "Quiet days + occasional hikes = perfect balance.",
    likes: 57,
    comments: 6,
    time: "1w",
  },
  {
    id: "p-9",
    author: "Ayla",
    badge: "ENTJ",
    astro: "Capricorn",
    stats: "8 5",
    content: "I optimize for peace, but schedule the adventures.",
    likes: 173,
    comments: 18,
    time: "5d",
  },
];

export const relatedPosts = [
  {
    id: "r-1",
    code: "6jIZhM",
    title: "How often do you actually want to travel?",
    description: "Question of the Day",
    tag: "Question of the Day",
    date: "1/28/2026",
    likes: 224,
    comments: 2041,
  },
  {
    id: "r-2",
    code: "HTOrqs",
    title: "If your life had a tagline, what would it say?",
    description: "Question of the Day",
    tag: "Question of the Day",
    date: "1/26/2026",
    likes: 246,
    comments: 2814,
  },
  {
    id: "r-3",
    code: "7Wvb8Q",
    title:
      "How do you determine whether a person is a good match for you? Do you get to know them or do you judge by the cover?",
    description: "Question of the Day",
    tag: "Question of the Day",
    date: "1/27/2026",
    likes: 285,
    comments: 2696,
  },
  {
    id: "r-4",
    code: "q3mX1A",
    title: "If you could relive any age, which would it be?",
    description: "Question of the Day",
    tag: "Question of the Day",
    date: "1/22/2026",
    likes: 312,
    comments: 2649,
  },
];
